from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable

from .schemas import NormalizedRecord, PredictionRecord

QUERY_KEYS = ("query", "claim", "question", "text")
LABEL_KEYS = ("gold_label", "label", "verdict", "stance", "target")
ID_KEYS = ("sample_id", "id", "claim_id", "qid")


def _pick(data: dict[str, Any], keys: tuple[str, ...], default: Any = "") -> Any:
    for key in keys:
        if key in data and data[key] is not None:
            return data[key]
    return default


def read_jsonl(path: str | Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    # Accept UTF-8 BOM files generated by some Windows tools.
    with Path(path).open("r", encoding="utf-8-sig") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def write_jsonl(path: str | Path, rows: Iterable[dict[str, Any]]) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")


def normalize_records(
    rows: list[dict[str, Any]],
    dataset: str,
    allow_unlabeled: bool = False,
) -> list[NormalizedRecord]:
    normalized: list[NormalizedRecord] = []
    for idx, row in enumerate(rows):
        sample_id = str(_pick(row, ID_KEYS, f"{dataset}-{idx}"))
        query = str(_pick(row, QUERY_KEYS, ""))
        label_raw = _pick(row, LABEL_KEYS, None)
        if label_raw is None or str(label_raw).strip() == "":
            if not allow_unlabeled:
                raise ValueError(
                    f"Missing label for dataset='{dataset}', sample_id='{sample_id}'. "
                    "Pass --allow-unlabeled for preprocessing-only flows."
                )
            label = "__unlabeled__"
        else:
            label = str(label_raw)
        metadata = row.get("metadata") if isinstance(row.get("metadata"), dict) else {}
        normalized.append(
            NormalizedRecord(
                sample_id=sample_id,
                dataset=dataset,
                query=query,
                gold_label=label,
                metadata=metadata,
            )
        )
    return normalized


def normalized_to_dict(records: list[NormalizedRecord]) -> list[dict[str, Any]]:
    return [
        {
            "sample_id": r.sample_id,
            "dataset": r.dataset,
            "query": r.query,
            "gold_label": r.gold_label,
            "metadata": r.metadata,
        }
        for r in records
    ]


def read_predictions(rows: list[dict[str, Any]]) -> list[PredictionRecord]:
    predictions: list[PredictionRecord] = []
    for idx, row in enumerate(rows):
        sample_id = str(_pick(row, ID_KEYS, f"pred-{idx}"))
        pred = row.get("predicted_label")
        if pred is None:
            pred = row.get("prediction")
        score = row.get("score")
        if score is not None:
            try:
                score = float(score)
            except (TypeError, ValueError):
                score = None
        metadata = row.get("metadata") if isinstance(row.get("metadata"), dict) else {}
        predictions.append(PredictionRecord(sample_id=sample_id, predicted_label=pred, score=score, metadata=metadata))
    return predictions
